### ISSUE TITLE
Missing Hyphenation

### ISSUE THREAD

**Issue by klavergne** [standardebooks/jane-austen_pride-and-prejudice#7]
This book is missing hyphenation as added by `se hyphenate`.

**Comment by acabal** [comment]
`se hyphenate` inserts soft hyphens for the 'compatible' epub builds. It's not used on our actual Github source, rather it's part of our build process to produce our compatible epubs.

**Comment by klavergne** [comment]
I downloaded the compatible epub build from the site, and it did not have soft hyphens. Maybe that step didn't happen during the build process.

**Comment by acabal** [comment]
Sorry I misspoke, only the Kindle version gets soft hyphens.

**Comment by klavergne** [comment]
Is there a reason epubs don't get them? They seem to work well.

**Comment by acabal** [comment]
They only work on certain ereaders. Most ereaders actually have poor soft hyphen support. The compatible epubs must work reasonable well on the widest number of ereaders, and sometimes that means not doing nice things like soft hyphens.
